[package]
name = "compiler-rs"
version = "0.1.0"
edition = "2018"
repository = "https://github.com/rustatian/compiler-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
